lib/localeapp/missing_translations.rb

There's no reason to use an array here `Set` is a much better choice.

Use a set to lookup missing translations

---

lib/localeapp/exception_handler.rb
spec/localeapp/exception_handler_spec.rb

When including user-input in `I18n.t`-calls malicious HTML may be
displayed and cause security issues.
See rails/rails@e8d57f3

Fix XSS vulnerability

---

CHANGELOG.md
lib/localeapp/routes.rb
lib/localeapp/routes/base.rb
localeapp.gemspec
spec/localeapp/routes_spec.rb

We rely on rack for `Rack::Utils.escape`, which itself rely on
`URI.encode_www_form_component`, so we better use this last one
directly, and not depend on rack anymore.

Remove rack dependency

---

Appraisals

Support for i18n ~> 0.3 was dropped in 3b8754d
[ci skip]

Remove entry for i18n gem ~> 0.3 in appraisal config

---

Gemfile
gemfiles/i18n_0.4.gemfile
gemfiles/i18n_0.5.gemfile
gemfiles/i18n_0.6.gemfile
gemfiles/i18n_0.7.gemfile

Older versions are vulnerable to CVE-2009-4123
http://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2009-4123

Force `jruby-openssl' dependency to a recent release

---

lib/localeapp.rb

It was added in b35e835, but we do not support ruby 1.8 anymore.

Remove ruby 1.8 workaround

---

localeapp.gemspec

We introduced this gem in 868811f to manage our documentation in
"textile" format, but we don't have any since 3f9bc02.

Remove unused `RedCloth' gem dependency declaration

---

.travis.yml

As of 20160916, default travis CI env use obsolete releases for jruby:
jruby-9.0.5.0
jruby-9.0.4.0
jruby-9.0.3.0
jruby-9.0.1.0
jruby-9.0.0.0.pre2
jruby-9.0.0.0.pre1
jruby-9.0.0.0
jruby-1.7.9-d19
jruby-1.7.20
jruby-1.7.19
jruby-1.7.18
jruby-1.7.17
jruby-1.7.11
jruby stable versions are now 9.1.x, and the last supported release on
1.7 was 1.7.26 (old stable).
Forcing the usage of their "Ubuntu 14.04" image, which seems more
actively maintained, is done by setting `sudo` to `required` and `dist`
to `trusty`. Note: setting `sudo` to `false` uses "Ubuntu 14.04" image,
but a different version that would bring jruby 1.7.26.
Travis CI uses RVM to manage ruby versions, but unfortunately it is
not up to date and install old release in most cases (2.4.0rc1 for 2.4,
and 2.3.1p112 for 2.3, etc.).
It's …

Improve travis CI build

---

spec/localeapp/updater_spec.rb

* Fix the condition for ruby platform (`!RUBY_PLATFORM == "jruby"` will
*always* return `false`) and compare with `java` so that this test is
run;
* Fix incorrect expectation, this test never passed but we could not
notice as it was never executed:
+ Remove explicit match on `!` (non-specific tag property);
* Remove quotes from pattern (we don't care about their presence or
which kind of quote is used in this test).
* Refactor regexp pattern (repetition).

Fix spec on `Localeapp::Updater' YAML dump formatting

---

.travis.yml
CHANGELOG.md
README.md
lib/localeapp.rb
lib/localeapp/updater.rb
localeapp.gemspec
spec/localeapp/updater_spec.rb

This change is based on original work from @deivid-rodriguez, thanks!
See original version at:
https://github.com/Locale/localeapp/pull/203

Remove support for ruby 1.9 and ruby 2.0

---

localeapp.gemspec

In 4fccfba we added version requirements for a few gems, most
probably to workaround build errors on old MRI release. However most
of these requirements are too strict and prevent usage with rails 5 or
`json` and `rest-cient` gems.
* Remove `mime-types` gem dependency requirement: not a direct
dependency;
* Remove version requirements for `json` gem and `rest-client` gem.

Simplify runtime dependencies in gem specification

---

spec/localeapp/cli/install_spec.rb

* Remove dead code;
* Remove contrived mocks on `Localeapp::CLI::Install#installer` which
might better be a private method, replace with mocks on installers
class methods, since we already depended on class names anyway;
* Refactor.

Improve `Localeapp::CLI::Install#execute' specs

---

bin/localeapp

We need to include `GLI::App` or `GLI` in a wrapper module, else the
methods from `GLI::AppSupport` are defined in the global namespace.

Fix the inclusion of GLI DSL in the global namespace

---

.autotest
.rvmrc

Those are config files for external tools which may have been used by
this gem authors, but they shouldn't be maintained in the gem sources
repository.

Remove config files for tools not used by project

---

.travis.yml

We specified builds only with custom gemfiles, to test against
specific releases of i18n (0.4, 0.5, 0.6 and 0.7). But build with the
standard gemfile is missing, we need to test with i18n actual version
too (0.8 currently).

Run tests with actual dependencies on travis CI

---

features/pull.feature

When `log` directory does not exist, the `pull` command fails, but we
never noticed it because we used `When I run` cucumber step from aruba
instead of `When I successfully run`, and we did not test the exit
status.

Fix setup (log directory) in `pull' command tests

---

features/add.feature
features/bad_command.feature
features/help.feature
features/install.feature
features/mv.feature
features/pull.feature
features/push.feature
features/rm.feature
features/step_definitions/cli_steps.rb
features/step_definitions/execution_steps.rb
features/update.feature

* Add missing expectations on localeapp execution return status;
* Remove steps testing that help is not displayed: most probably it was
a way to ensure this command exist, but we have a dedicated test for
unknown commands (`bad_command.feature'), and we should generally test
what known commands do, not what they don't do.
---
Currently depends on #231, #232.

Fix exit status expectations in user acceptance test

---

features/step_definitions/cli_steps.rb

We changed the response for this action on the API service, it now
returns a JSON response on success, which includes the import
identifier.

Update UAT fixtures for projects/import API action

---

bin/localeapp
features/add.feature
features/mv.feature
features/pull.feature
features/push.feature
features/rm.feature
features/step_definitions/cli_steps.rb
features/support/env.rb
features/update.feature
lib/localeapp.rb
lib/localeapp/cli/pull.rb
lib/localeapp/cli/push.rb
lib/localeapp/cli/remove.rb
lib/localeapp/cli/rename.rb
lib/localeapp/poller.rb
lib/localeapp/sender.rb
spec/localeapp/cli/pull_spec.rb
spec/localeapp/cli/push_spec.rb
spec/localeapp/cli/rename_spec.rb

Use YAML instead of JSON for fakeweb in UAT
-------------------------------------------
Using YAML allows us to "mock" HTTP requests with regular expressions
instead of only strings.
---
Fix handling of HTTP errors when querying API
---------------------------------------------
In UAT we focus on 404 errors, which are triggered when using an
incorrect API key, but those changes should also handle other 4xx errors
correctly.

Fix handling of HTTP errors when querying API

---

lib/localeapp/cli/install.rb
spec/localeapp/cli/install_spec.rb

Any project created with a different default locale than `en` will
make the installer output a warning: we cannot know the default locale
configured for the current rails app, we would need to boot it.
Doing the check at runtime is complex, we would need to rely on a hook
like `Rails.application.config.after_initialize`, and at this time we
don't know the default locale for the Localeapp project. Requesting the
API at this time could prevent the app from booting correctly.

Stop checking project and app default locale at install

---

lib/localeapp/configuration.rb

Clarify usage of `Localeapp::Configuration#polling_environments`
attribute, after this issue was reported at:
https://github.com/Locale/localeapp/issues/165
Thanks @redbar0n for the contribution!
Fixes #165.

Fix comment on Localeapp::Configuration attributes

---

.travis.yml

For unknown reason, main build will use jruby version 9.1.9.0
successfully, but builds with alternate gem dependencies files attempts
to use 9.1.15.0200 and fail:
$ rvm use jruby --install --binary --fuzzy
Unknown ruby string (do not know how to handle): jruby-9.1.15.0200.
Required jruby-9.1.15.0200 is not installed - installing.
Unknown ruby string (do not know how to handle): jruby-9.1.15.0200.
Searching for binary rubies, this might take some time.
Unknown ruby string (do not know how to handle): jruby-9.1.15.0200.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm jruby-9.1.15.0200 do rvm gemset create ' first, or append '--create'.
We force version 9.1.15.0 here, which is latest jruby stable version. …

Force jruby version 9.1.15.0 on travis CI

---

lib/localeapp/exception_handler.rb
spec/localeapp/exception_handler_spec.rb

Hello,
I have been trying Localeapp for a few weeks now and I have run into some things I think that can be improved. This first one I'm submitting is this one to make the log messages a bit clearer. I am using WillPaginate and it uses scoped translations. It gave a difference in the output of the log messages:
```ruby
** [Localeapp] translation missing: nl.will_paginate.organization.page_entries_info.single_page_html
** [Localeapp] Detected missing translation for key(s) ["organization.page_entries_info.single_page_html"]
```
As you can see the key registered in the second log message is missing the scope. One might add the wrong translation because of that. I have changed the code to include the scope in the log message. It looks like this now:
```ruby
** [Localeapp] translation …
```

Scope keys in ExceptionHandler log messages

---

lib/localeapp/rails/force_exception_handler_in_translation_helper.rb

Hello again :wave:,
I experienced a little challenge when using this gem together with [WillPaginate](https://github.com/mislav/will_paginate). In this PR I propose a change to the code that addresses the issue I experienced.
WillPaginate has a [`page_entries_info`](https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers.rb#L99-L160) method to add info about the page entries to a view. It first looks for a model-specific translation and when it can not be found it will fall back to a generic translation. It uses [ActionView's translation helper](https://github.com/rails/rails/blob/56832e791f3ec3e586cf049c6408c7a183fdd3a1/actionview/lib/action_view/helpers/translation_helper.rb#L59-L111) that will ensure falling back on to the default translation option. However, …

Don't add {:raise => false} to options for blacklisted keys

---

localeapp.gemspec

To address security issues, we now force `json` and `rest-client`
to versions without known vulnerabilities.
This should avoid the following vulnerabilities:
* OSVDB-101157
* CVE-2015-3448 / OSVDB-117461
* CVE-2013-0269 / OSVDB-101137
* CVE-2015-1820 / OSVDB-119878

Update vulnerable dependencies

---

lib/localeapp/rails/force_exception_handler_in_translation_helper.rb

This bug happens when blacklisted keys pattern is nil
(_i.e._ when the user has not configured it in its application).
It's due to `String#match?` not handling `nil` as parameter.
We fix it by using `String#=~` instead, which does handle nil as
parameter (and considers it never matching, which is what we want).
This bug was introduced in 4e46de6080f3810be7ea76868f228b4d2d11afaa

Fix a TypeMismatch error in ExceptionHandler

---

CHANGELOG.md
lib/localeapp/updater.rb

We don't support I18n v1.3 because we rely on Hash#deep_merge!
monkey patch which was removed in this version. We now use our own
implementation to avoid this kind of issue.

Remove I18n Hash#deep_merge! usage

---

bin/localeapp

As reported in #262, `.env` can sometimes be a directory, in which case, any CLI command fails with `Errno::EISDIR: Is a directory @ io_fread`.
This commit checks that `.env` is a regular file before trying to read it.

Fix a crash when .env is a directory

---

lib/localeapp/rails.rb

Autoloading during initialization is going to be an error condition in future versions of Rails.
This commit fixes the deprecation warning displayed in rails 6.
https://github.com/rails/rails/issues/36546
Fix #276

Fix deprecation warning regarding Autoloading

---

lib/localeapp/rails/force_exception_handler_in_translation_helper.rb

Ruby 3.0 introduced changes described here: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
Simplest solution would be to use double splat operator, that was introduced since ruby 2.0.

ruby 3.0 / rails 6.1 incompatibility issue #284

---

lib/localeapp.rb
lib/localeapp/rails/backport_translation_helper_fix_to_honor_raise_option.rb

Remove `i18n/core_ext/hash` dependency to support i18n 1.9. Fixes #287.

Support i18n 1.9
